dist: xenial
dotnet: 2.2.203

cache:
    directories: uit.hotel.client\node_modules
matrix:
    include:
        - language: node_js
          node_js: 10.15.3
          env: ❤ = NodeJS Lint + Build + Test
          script:
              - cd uit.hotel.client
              - yarn
              - yarn lint
              - yarn build
              - yarn test

        - language: csharp
          os: linux
          mono: none
          env: ❤ = C# Build + Test
          script:
              - dotnet --info
              - dotnet restore
              - dotnet build
              - dotnet test uit.hotel.test
